export const MAIN_ROUTE = "/"
export const LOGIN_ROUTE = "/login"
export const REGISTER_ROUTE = "/registration"
export const PROFILE_ROUTE = "/profile"
export const ERROR_PAGE = "/error"
export const LINK_TO_MAIN_RESOURCE = "https://t.me/SmartBOT_investbot"
